//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.18.0
//     from Assets/InputControl.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace skyclad.input
{
    /// <summary>
    /// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/InputControl.inputactions".
    /// </summary>
    /// <remarks>
    /// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
    /// </remarks>
    /// <example>
    /// <code>
    /// using namespace UnityEngine;
    /// using UnityEngine.InputSystem;
    ///
    /// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
    /// public class Example : MonoBehaviour, MyActions.IPlayerActions
    /// {
    ///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
    ///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
    ///
    ///     void Awake()
    ///     {
    ///         m_Actions = new MyActions_Actions();              // Create asset object.
    ///         m_Player = m_Actions.Player;                      // Extract action map object.
    ///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
    ///     }
    ///
    ///     void OnDestroy()
    ///     {
    ///         m_Actions.Dispose();                              // Destroy asset object.
    ///     }
    ///
    ///     void OnEnable()
    ///     {
    ///         m_Player.Enable();                                // Enable all actions within map.
    ///     }
    ///
    ///     void OnDisable()
    ///     {
    ///         m_Player.Disable();                               // Disable all actions within map.
    ///     }
    ///
    ///     #region Interface implementation of MyActions.IPlayerActions
    ///
    ///     // Invoked when "Move" action is either started, performed or canceled.
    ///     public void OnMove(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
    ///     }
    ///
    ///     // Invoked when "Attack" action is either started, performed or canceled.
    ///     public void OnAttack(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
    ///     }
    ///
    ///     #endregion
    /// }
    /// </code>
    /// </example>
    public partial class @InputControl: IInputActionCollection2, IDisposable
    {
        /// <summary>
        /// Provides access to the underlying asset instance.
        /// </summary>
        public InputActionAsset asset { get; }

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public @InputControl()
        {
            asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""InputControl"",
    ""maps"": [
        {
            ""name"": ""player"",
            ""id"": ""da9bf091-08a1-476c-b5db-5ee5421736a9"",
            ""actions"": [
                {
                    ""name"": ""axis0"",
                    ""type"": ""Value"",
                    ""id"": ""2e3a17bb-8b65-4bdf-b778-179bfb6ac0cd"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""axis1"",
                    ""type"": ""Value"",
                    ""id"": ""53a97c53-4984-40f0-a29f-ffb5091b8ef6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""button0"",
                    ""type"": ""Button"",
                    ""id"": ""a22a64de-59b9-403d-92b9-58432f71d180"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""button1"",
                    ""type"": ""Button"",
                    ""id"": ""e2b719fb-07ba-46cd-a7d8-c210514d98a0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""button2"",
                    ""type"": ""Button"",
                    ""id"": ""5290e4ab-553f-487d-b7f5-55088d9e6fcd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""button3"",
                    ""type"": ""Button"",
                    ""id"": ""fef84f9a-b358-421b-8ddf-6552790cc9b5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""start"",
                    ""type"": ""Button"",
                    ""id"": ""5bfa75c8-3b2c-45dc-8c17-a2b15918c2b3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""select"",
                    ""type"": ""Button"",
                    ""id"": ""af3ace42-7725-46f3-814b-164fa830a6f8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""triggerl"",
                    ""type"": ""Button"",
                    ""id"": ""8941eb37-5efd-4ea3-9d27-28ef3ebd0f3d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""triggerr"",
                    ""type"": ""Button"",
                    ""id"": ""9064cd9d-39b8-49d3-8fc8-16e1172d77b9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""bumperl"",
                    ""type"": ""Button"",
                    ""id"": ""fa340fd5-bcbf-4da6-8055-9aa566248e58"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""bumperr"",
                    ""type"": ""Button"",
                    ""id"": ""126571e2-d289-4337-ac24-f4830b75309c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""stickl"",
                    ""type"": ""Button"",
                    ""id"": ""14b9b3ab-8fda-4074-abd4-218073e2f385"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""stickr"",
                    ""type"": ""Button"",
                    ""id"": ""6882dff5-3e3f-4736-b543-9e1ffc9f616f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1b8e3725-ea8b-4c62-8d3c-9999b66b59d7"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""axis0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""7f55d66f-cceb-4c17-bdd3-23e8ee9b86a0"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""axis0"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6291fb10-0e06-491a-a8ca-f4d8b0e53d79"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""axis0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9d27a9bd-5541-49c6-97b0-59260d189efb"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""axis0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b1b930f0-f57c-4cc1-96ea-94e7f442be25"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""axis0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""19ae4966-d2d0-4948-83e9-d9603d753e0c"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""axis0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""386b0217-1b37-45d8-91d6-211615697469"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""axis1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""071f72ed-1c91-4579-9f29-8039f7cd02ac"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""axis1"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ad3a5ab9-1bc5-4cbe-9d04-52037ee1d807"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""axis1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""2437651f-8584-447d-bd38-f33373c38298"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""axis1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""bdbdb2a4-b9f6-4794-a2ac-e895a0502a40"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""axis1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ff969c22-b59d-46e3-bf87-7bce808261f3"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""axis1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""3bc79b5f-41bd-40cd-a3c2-174f4d0948af"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""button0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2215ea59-238f-420c-9224-f86aef780f02"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""button1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f594b93a-a8cf-463f-b30d-e91831e0512e"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""button2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c7e8d4c-f090-4a44-8242-fc0566955912"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""button3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b802560-97bf-4ef2-8249-5de06891b4c0"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""triggerl"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""582e2665-0acd-4e7c-bd25-9ee291091b80"",
                    ""path"": ""<Keyboard>/rightCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""triggerr"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""df947e3d-e8e9-4a6e-9db2-712741dce306"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""bumperl"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8f654f92-b74a-4db4-ab28-79d78ec93798"",
                    ""path"": ""<Keyboard>/rightShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""bumperr"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""97f10ddc-b0de-478c-bf81-9c28ef1cccd0"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""90867217-28f6-4791-a8bb-e283aa1f703d"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""320f04b5-ea4e-4a53-825c-838cfb6545af"",
                    ""path"": ""<Keyboard>/leftAlt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""stickl"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8211adb1-ab96-46cb-9610-635603499b68"",
                    ""path"": ""<Keyboard>/rightAlt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""stickr"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // player
            m_player = asset.FindActionMap("player", throwIfNotFound: true);
            m_player_axis0 = m_player.FindAction("axis0", throwIfNotFound: true);
            m_player_axis1 = m_player.FindAction("axis1", throwIfNotFound: true);
            m_player_button0 = m_player.FindAction("button0", throwIfNotFound: true);
            m_player_button1 = m_player.FindAction("button1", throwIfNotFound: true);
            m_player_button2 = m_player.FindAction("button2", throwIfNotFound: true);
            m_player_button3 = m_player.FindAction("button3", throwIfNotFound: true);
            m_player_start = m_player.FindAction("start", throwIfNotFound: true);
            m_player_select = m_player.FindAction("select", throwIfNotFound: true);
            m_player_triggerl = m_player.FindAction("triggerl", throwIfNotFound: true);
            m_player_triggerr = m_player.FindAction("triggerr", throwIfNotFound: true);
            m_player_bumperl = m_player.FindAction("bumperl", throwIfNotFound: true);
            m_player_bumperr = m_player.FindAction("bumperr", throwIfNotFound: true);
            m_player_stickl = m_player.FindAction("stickl", throwIfNotFound: true);
            m_player_stickr = m_player.FindAction("stickr", throwIfNotFound: true);
        }

        ~@InputControl()
        {
            UnityEngine.Debug.Assert(!m_player.enabled, "This will cause a leak and performance issues, InputControl.player.Disable() has not been called.");
        }

        /// <summary>
        /// Destroys this asset and all associated <see cref="InputAction"/> instances.
        /// </summary>
        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
        public void Enable()
        {
            asset.Enable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
        public void Disable()
        {
            asset.Disable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
        public IEnumerable<InputBinding> bindings => asset.bindings;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // player
        private readonly InputActionMap m_player;
        private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
        private readonly InputAction m_player_axis0;
        private readonly InputAction m_player_axis1;
        private readonly InputAction m_player_button0;
        private readonly InputAction m_player_button1;
        private readonly InputAction m_player_button2;
        private readonly InputAction m_player_button3;
        private readonly InputAction m_player_start;
        private readonly InputAction m_player_select;
        private readonly InputAction m_player_triggerl;
        private readonly InputAction m_player_triggerr;
        private readonly InputAction m_player_bumperl;
        private readonly InputAction m_player_bumperr;
        private readonly InputAction m_player_stickl;
        private readonly InputAction m_player_stickr;
        /// <summary>
        /// Provides access to input actions defined in input action map "player".
        /// </summary>
        public struct PlayerActions
        {
            private @InputControl m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public PlayerActions(@InputControl wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "player/axis0".
            /// </summary>
            public InputAction @axis0 => m_Wrapper.m_player_axis0;
            /// <summary>
            /// Provides access to the underlying input action "player/axis1".
            /// </summary>
            public InputAction @axis1 => m_Wrapper.m_player_axis1;
            /// <summary>
            /// Provides access to the underlying input action "player/button0".
            /// </summary>
            public InputAction @button0 => m_Wrapper.m_player_button0;
            /// <summary>
            /// Provides access to the underlying input action "player/button1".
            /// </summary>
            public InputAction @button1 => m_Wrapper.m_player_button1;
            /// <summary>
            /// Provides access to the underlying input action "player/button2".
            /// </summary>
            public InputAction @button2 => m_Wrapper.m_player_button2;
            /// <summary>
            /// Provides access to the underlying input action "player/button3".
            /// </summary>
            public InputAction @button3 => m_Wrapper.m_player_button3;
            /// <summary>
            /// Provides access to the underlying input action "player/start".
            /// </summary>
            public InputAction @start => m_Wrapper.m_player_start;
            /// <summary>
            /// Provides access to the underlying input action "player/select".
            /// </summary>
            public InputAction @select => m_Wrapper.m_player_select;
            /// <summary>
            /// Provides access to the underlying input action "player/triggerl".
            /// </summary>
            public InputAction @triggerl => m_Wrapper.m_player_triggerl;
            /// <summary>
            /// Provides access to the underlying input action "player/triggerr".
            /// </summary>
            public InputAction @triggerr => m_Wrapper.m_player_triggerr;
            /// <summary>
            /// Provides access to the underlying input action "player/bumperl".
            /// </summary>
            public InputAction @bumperl => m_Wrapper.m_player_bumperl;
            /// <summary>
            /// Provides access to the underlying input action "player/bumperr".
            /// </summary>
            public InputAction @bumperr => m_Wrapper.m_player_bumperr;
            /// <summary>
            /// Provides access to the underlying input action "player/stickl".
            /// </summary>
            public InputAction @stickl => m_Wrapper.m_player_stickl;
            /// <summary>
            /// Provides access to the underlying input action "player/stickr".
            /// </summary>
            public InputAction @stickr => m_Wrapper.m_player_stickr;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_player; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="PlayerActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="PlayerActions" />
            public void AddCallbacks(IPlayerActions instance)
            {
                if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
                @axis0.started += instance.OnAxis0;
                @axis0.performed += instance.OnAxis0;
                @axis0.canceled += instance.OnAxis0;
                @axis1.started += instance.OnAxis1;
                @axis1.performed += instance.OnAxis1;
                @axis1.canceled += instance.OnAxis1;
                @button0.started += instance.OnButton0;
                @button0.performed += instance.OnButton0;
                @button0.canceled += instance.OnButton0;
                @button1.started += instance.OnButton1;
                @button1.performed += instance.OnButton1;
                @button1.canceled += instance.OnButton1;
                @button2.started += instance.OnButton2;
                @button2.performed += instance.OnButton2;
                @button2.canceled += instance.OnButton2;
                @button3.started += instance.OnButton3;
                @button3.performed += instance.OnButton3;
                @button3.canceled += instance.OnButton3;
                @start.started += instance.OnStart;
                @start.performed += instance.OnStart;
                @start.canceled += instance.OnStart;
                @select.started += instance.OnSelect;
                @select.performed += instance.OnSelect;
                @select.canceled += instance.OnSelect;
                @triggerl.started += instance.OnTriggerl;
                @triggerl.performed += instance.OnTriggerl;
                @triggerl.canceled += instance.OnTriggerl;
                @triggerr.started += instance.OnTriggerr;
                @triggerr.performed += instance.OnTriggerr;
                @triggerr.canceled += instance.OnTriggerr;
                @bumperl.started += instance.OnBumperl;
                @bumperl.performed += instance.OnBumperl;
                @bumperl.canceled += instance.OnBumperl;
                @bumperr.started += instance.OnBumperr;
                @bumperr.performed += instance.OnBumperr;
                @bumperr.canceled += instance.OnBumperr;
                @stickl.started += instance.OnStickl;
                @stickl.performed += instance.OnStickl;
                @stickl.canceled += instance.OnStickl;
                @stickr.started += instance.OnStickr;
                @stickr.performed += instance.OnStickr;
                @stickr.canceled += instance.OnStickr;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="PlayerActions" />
            private void UnregisterCallbacks(IPlayerActions instance)
            {
                @axis0.started -= instance.OnAxis0;
                @axis0.performed -= instance.OnAxis0;
                @axis0.canceled -= instance.OnAxis0;
                @axis1.started -= instance.OnAxis1;
                @axis1.performed -= instance.OnAxis1;
                @axis1.canceled -= instance.OnAxis1;
                @button0.started -= instance.OnButton0;
                @button0.performed -= instance.OnButton0;
                @button0.canceled -= instance.OnButton0;
                @button1.started -= instance.OnButton1;
                @button1.performed -= instance.OnButton1;
                @button1.canceled -= instance.OnButton1;
                @button2.started -= instance.OnButton2;
                @button2.performed -= instance.OnButton2;
                @button2.canceled -= instance.OnButton2;
                @button3.started -= instance.OnButton3;
                @button3.performed -= instance.OnButton3;
                @button3.canceled -= instance.OnButton3;
                @start.started -= instance.OnStart;
                @start.performed -= instance.OnStart;
                @start.canceled -= instance.OnStart;
                @select.started -= instance.OnSelect;
                @select.performed -= instance.OnSelect;
                @select.canceled -= instance.OnSelect;
                @triggerl.started -= instance.OnTriggerl;
                @triggerl.performed -= instance.OnTriggerl;
                @triggerl.canceled -= instance.OnTriggerl;
                @triggerr.started -= instance.OnTriggerr;
                @triggerr.performed -= instance.OnTriggerr;
                @triggerr.canceled -= instance.OnTriggerr;
                @bumperl.started -= instance.OnBumperl;
                @bumperl.performed -= instance.OnBumperl;
                @bumperl.canceled -= instance.OnBumperl;
                @bumperr.started -= instance.OnBumperr;
                @bumperr.performed -= instance.OnBumperr;
                @bumperr.canceled -= instance.OnBumperr;
                @stickl.started -= instance.OnStickl;
                @stickl.performed -= instance.OnStickl;
                @stickl.canceled -= instance.OnStickl;
                @stickr.started -= instance.OnStickr;
                @stickr.performed -= instance.OnStickr;
                @stickr.canceled -= instance.OnStickr;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PlayerActions.UnregisterCallbacks(IPlayerActions)" />.
            /// </summary>
            /// <seealso cref="PlayerActions.UnregisterCallbacks(IPlayerActions)" />
            public void RemoveCallbacks(IPlayerActions instance)
            {
                if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="PlayerActions.AddCallbacks(IPlayerActions)" />
            /// <seealso cref="PlayerActions.RemoveCallbacks(IPlayerActions)" />
            /// <seealso cref="PlayerActions.UnregisterCallbacks(IPlayerActions)" />
            public void SetCallbacks(IPlayerActions instance)
            {
                foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="PlayerActions" /> instance referencing this action map.
        /// </summary>
        public PlayerActions @player => new PlayerActions(this);
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "player" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="PlayerActions.AddCallbacks(IPlayerActions)" />
        /// <seealso cref="PlayerActions.RemoveCallbacks(IPlayerActions)" />
        public interface IPlayerActions
        {
            /// <summary>
            /// Method invoked when associated input action "axis0" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnAxis0(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "axis1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnAxis1(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "button0" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnButton0(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "button1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnButton1(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "button2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnButton2(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "button3" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnButton3(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "start" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnStart(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "select" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnSelect(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "triggerl" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnTriggerl(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "triggerr" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnTriggerr(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "bumperl" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnBumperl(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "bumperr" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnBumperr(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "stickl" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnStickl(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "stickr" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnStickr(InputAction.CallbackContext context);
        }
    }
}
